### PR TITLE
Fix: hide keyboard on Android

### LINKED ISSUE #229: Hide keyboard does not work on Android
Maestro: 1.8.1

### PR DESCRIPTION
**Pull request by dmitry-zaitsev**
## Testing
Tested on an emulator

## Issues Fixed

`hideKeyboard` was not always working

Fixes #229

### CODE REVIEW

**Review by Leland-Takamine — APPROVED** [review]

File: maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt [hunk 1]
```diff
@@ -261,6 +261,7 @@ class AndroidDriver(
 
     override fun hideKeyboard() {
         dadb.shell("input keyevent 66")
+        dadb.shell("input keyevent 111")
```
Comment (amanjeetsingh150) [inline maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt:264]: Is this because this key is mapped differently 🤔 ?

Comment (dmitry-zaitsev) [reply maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt:264]: Might be different OS versions or due to different vendors. I was never able to reproduce the first case but another dev reported that code 66 worked for them
