### PR TITLE
Ensure recordings and screenshots create relative directories when specified

### LINKED ISSUE #2483: startRecording does not create directory
### Is there an existing issue for this?

- [x] I have searched the existing issues and didn't find mine.

### Steps to reproduce

Use `startRecording` with a path for which the directory does not exist.

### Actual results

The test run crashes with the following error:

<details>
<summary>Stacktrace</summary>

java.io.FileNotFoundException: notexisting/path/to/video.mp4 (No such file or directory)                         
        at java.base/java.io.FileOutputStream.open0(Native Method)                                                                    
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:289)                                                         
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:230)                                                       
        at okio.Okio__JvmOkioKt.sink(JvmOkio.kt:173)                                                                                  
        at okio.Okio.sink(Unknown Source)                                                                                             
        at okio.Okio__JvmOkioKt.sink$default(JvmOkio.kt:173)                                                                          
        at okio.Okio.sink$default(Unknown Source)                                                                                     
        at maestro.orchestra.Orchestra.startRecordingCommand(Orchestra.kt:854)                                                        
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:325)                                                               
        at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:212)                                                              
        at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:143)                                                                      
        at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:189)                                           
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:71)                                                  
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:62)                                                  
        at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:179)                                                               
        at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:62)                                                                  
        at maestro.cli.command.TestCommand.runSingleFlow(TestCommand.kt:389)                                                          
        at maestro.cli.command.TestCommand.access$runSingleFlow(TestCommand.kt:65)                                                    
        at maestro.cli.command.TestCommand$runShardSuite$2.invoke(TestCommand.kt:364)                                                 
        at maestro.cli.command.TestCommand$runShardSuite$2.invoke(TestCommand.kt:333)                                                 
        at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:112)                                         
        at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:54)                                  
        at maestro.cli.command.TestCommand.runShardSuite(TestCommand.kt:333)                                                          
        at maestro.cli.command.TestCommand.access$runShardSuite(TestCommand.kt:65)                                                    
        at maestro.cli.command.TestCommand$handleSessions$1$results$1$1.invokeSuspend(TestCommand.kt:300)                             
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                                     
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)                                                               
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)                                         
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)                                                                    
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)                                      
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)                             
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)                               
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)            

</details>

### Expected results

Directory should be created, as it is for `takeScreenshot`.

### About app

This is a React Native app using Expo, but I doubt that it has anything to do with the framework.

### About environment

Apple M4 Pro (arm64), Macbook Pro, macOS Sequoia 15.4.1.

openjdk version "21.0.7" 2025-04-15 LTS
OpenJDK Runtime Environment Temurin-21.0.7+6 (build 21.0.7+6-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.7+6 (build 21.0.7+6-LTS, mixed mode, sharing)

### Logs

_No response_

### Maestro version

1.40.0

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Fishbowler**
## Proposed changes

- Resolve and create directories for screenRecording
- Unify implementation with takeScreenshot
- Stop using deprecated takeScreenshot method

## Testing

New integration tests

## Issues fixed

Fixes #2483

### CODE REVIEW

File: maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt [hunk 1]
```diff
@@ -1454,6 +1449,22 @@ class Orchestra(
...
+        // Work out relative v absolute input
+        val resolvedFile = parentPath?.resolve(filePathStr)?.toFile() ?: File(filePathStr)
+        val absoluteFile = resolvedFile.absoluteFile
+
+        if(absoluteFile.parentFile.exists() || absoluteFile.parentFile.mkdirs()) {
+            return resolvedFile
+                .sink()
+                .buffer()
+        } else {
+            throw MaestroException.DestinationIsNotWritable(
```
Comment (amanjeetsingh150) [inline maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt:1481]: This should not be maestro exception, is this a user issue? When we cannot create parent file I think it would fail during write which would throw IOException at some point which might be better.

Now a question could be how should we handle IOExceptions. Unless I see some reports I'm little hesitant to handle this, don't want to overcomplicate it.

Comment (Fishbowler) [reply maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt:1481]: I was attempting to make the smallest possible change.

This mirrors the logic in https://github.com/mobile-dev-inc/Maestro/blob/b81c01aeb1feab81288b35067ad8831159a7948a/maestro-client/src/main/java/maestro/Maestro.kt#L491-L502

**Comment by Fishbowler** [comment]
Rebased
