### PR TITLE
Multi-arch runners for iOS

### LINKED ISSUE #2932: iOS driver not ready - Xcode 26.2 / macOS 26.2 compatibility issue
## Description

Maestro 2.1.0 fails to start the XCTest driver on macOS 26.2 with Xcode 26.2. The driver installation appears to complete but never starts listening on port 7001.

## Environment

- **Maestro Version:** 2.1.0
- **OS Name:** Mac OS X
- **OS Version:** 26.2
- **Xcode Version:** 26.2
- **Architecture:** x86_64
- **Java Version:** 17
- **Simulator:** iPhone 15 Pro (iOS 17.5)

## Error

```
iOS driver not ready in time, consider increasing timeout by configuring MAESTRO_DRIVER_STARTUP_TIMEOUT env variable

xcuitest.installer.LocalXCTestInstaller$IOSDriverTimeoutException: iOS driver not ready in time
```

## Debug Log Analysis

From the debug log, the sequence is:
1. `[Start] Install XCUITest runner on F8FCBAA1-...`
2. `Running command line operation: [xcodebuild, test-without-building, -xctestrun, ...]`
3. `[Done] Running XcUITest with xcodebuild test-without-building` (completes immediately)
4. Repeated failures: `Failed to connect to /127.0.0.1:7001`

The `xcodebuild test-without-building` command completes instantly instead of keeping the test runner process alive.

## Steps to Reproduce

1. Install Xcode 26.2 on macOS 26.2
2. Boot an iOS simulator (tested with iOS 17.5)
3. Run any Maestro test: `maestro test myflow.yaml`

## What I've Tried

- `MAESTRO_DRIVER_STARTUP_TIMEOUT=300000` (5 minutes) - still times out
- `--reinstall-driver` flag - same result
- Fresh Maestro install via `curl -Ls "https://get.maestro.mobile.dev" | bash`
- Rebooting simulator
- Both iOS 17.5 and iOS 26.2 simulator runtimes

## Related Issues

- #2609 was closed as fixed in v2.0.5 for iOS 26 beta, but this appears to be a regression or new issue with Xcode 26.2 release version

## Expected Behavior

XCTest runner should start and listen on port 7001, allowing Maestro to connect and run tests.

## Actual Behavior

XCTest runner installation reports success but the process exits immediately, never opening port 7001.

### PR DESCRIPTION
**Pull request by Fishbowler**
## Proposed changes

Maestro v2.1.0 accidentally removed x86_64 support for iOS test runners. This restores Intel CPU support, and prevents it reoccuring.

## Testing

File sizes are now what they were before the change. Flows still run on arm64. I don't have an Intel Mac to test on.

## Issues fixed

#2932

### CODE REVIEW

File: maestro-ios-xctest-runner/build-maestro-ios-runner.sh [hunk 1]
```diff
@@ -36,7 +35,8 @@ xcodebuild clean build-for-testing \
   -derivedDataPath "$PWD/$DERIVED_DATA_PATH" \
   -scheme maestro-driver-ios \
   -destination "$DESTINATION" \
-  ARCHS="$ARCHS" ${DEVELOPMENT_TEAM_OPT}
+  ${ARCHS:+ARCHS="$ARCHS"}
+  ${DEVELOPMENT_TEAM_OPT}
```
Comment (amanjeetsingh150) [inline maestro-ios-xctest-runner/build-maestro-ios-runner.sh]: Hmmm, this is getting confusing shouldn't we just define in this script on the basis of DESTINATION which by default is iOS simulator. Something like:

```
 if [[ "$DESTINATION" == *"iOS Simulator"* ]]; then
    ARCHS="x86_64 arm64"
  else
    ARCHS="arm64"
  fi
```

And remove ARCHS altogether from build-maestro-ios-runner-all.sh

**Review by amanjeetsingh150 — APPROVED** [review]
Nice I see you've included the intel runner for testing.
