### PR TITLE
fix: condition for checking web flows in case flows length is zero

### LINKED ISSUE #2674: [2.0.0] executionOrder forces all tests to Chromium
### Is there an existing issue for this?

- [x] I have searched the existing issues and didn't find mine.

### Steps to reproduce

`./test.yaml`
```
appId: com.example
---
- launchApp
```

`./config.yaml`
```
flows:
  - '**'

executionOrder:
  flowsOrder:
    - 'test'
```
 
Run `maestro test .`

### Actual results

```
Device chromium was requested, but it is not connected.
```

### Expected results

Use the opened simulator/emulator

### About app

n/a - we don't get that far

### About environment

OS: MacOS 15.6.1

Java version:
```
openjdk version "17.0.14" 2025-01-21 LTS
OpenJDK Runtime Environment Zulu17.56+15-CA (build 17.0.14+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.56+15-CA (build 17.0.14+7-LTS, mixed mode, sharing)
```

### Logs

<details>
<summary>Logs</summary>

```
10:31:42.856 [ INFO] maestro.cli.report.TestDebugReporter.logSystemInfo: Debug output path: /Users/danc/.maestro/tests/2025-09-01_103142
10:31:42.857 [ INFO] MAESTRO.logSystemInfo: ---- System Info ----
10:31:42.857 [ INFO] MAESTRO.logSystemInfo: Maestro Version: 2.0.0
10:31:42.858 [ INFO] MAESTRO.logSystemInfo: CI: Undefined
10:31:42.858 [ INFO] MAESTRO.logSystemInfo: OS Name: Mac OS X
10:31:42.858 [ INFO] MAESTRO.logSystemInfo: OS Version: 15.6.1
10:31:42.858 [ INFO] MAESTRO.logSystemInfo: Architecture: aarch64
10:31:42.859 [ INFO] MAESTRO.logSystemInfo: Java Version: 17
10:31:42.901 [ INFO] MAESTRO.logSystemInfo: Xcode Version: 16.4
10:31:43.055 [DEBUG] io.micrometer.common.util.internal.logging.InternalLoggerFactory.newDefaultFactory: Using SLF4J as the default logging framework
10:31:43.059 [ INFO] MAESTRO.logSystemInfo: Flutter Version: 3.35.1
10:31:43.205 [ INFO] MAESTRO.logSystemInfo: Flutter Channel: stable
10:31:43.205 [ INFO] MAESTRO.logSystemInfo: ---------------------
10:31:43.469 [ INFO] maestro.orchestra.workspace.WorkspaceExecutionPlanner.plan: Created execution plan: ExecutionPlan(flowsToRun=[], sequence=FlowSequence(flows=[/Users/danc/git/maestro/issue-2674/./test.yaml], continueOnFailure=true), workspaceConfig=WorkspaceConfig(flows=[**], includeTags=null, excludeTags=null, local=null, executionOrder=ExecutionOrder(continueOnFailure=true, flowsOrder=[test]), baselineBranch=null, notifications=null, disableRetries=false, platform=PlatformConfiguration(android=AndroidConfiguration(disableAnimations=false), ios=IOSConfiguration(disableAnimations=false, snapshotKeyHonorModalViews=null)), testOutputDir=null))

```

</details>

### Maestro version

2.0.0

### How did you install Maestro?

Homebrew

### Anything else?

Running with `maestro -p android test .` should override this behaviour, but doesn't.

### PR DESCRIPTION
**Pull request by proksh**
In case the `executionOrder` was there and it has wrong name, that means `flows` are `0`. Which caused `allFlowsAreWebFlow` to give true.

Added the check for empty flows as well as included the sequenceFlow as well.

Fixes #2674

### CODE REVIEW

File: maestro-cli/src/main/java/maestro/cli/runner/TestSuiteInteractor.kt [hunk 1]
```diff
@@ -87,6 +87,8 @@ class TestSuiteInteractor(
             }
         }
 
+      PrintUtils.message(executionPlan.sequence.toString())
+
```
Comment (Fishbowler) [inline maestro-cli/src/main/java/maestro/cli/runner/TestSuiteInteractor.kt]: Is this a debug statement that's supposed to be removed?

Comment (proksh) [reply maestro-cli/src/main/java/maestro/cli/runner/TestSuiteInteractor.kt]: Yes, my bad

**Review by steviec — APPROVED** [review]
LTGM. The fact that `.all{}` always returns `true` for an empty list in Kotline is INSANE, in my humble opinion.

File: maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt [hunk 2]
```diff
@@ -201,12 +201,13 @@ class TestCommand : Callable<Int> {
...
-        return plan.flowsToRun.any { it.toFile().isWebFlow() } || 
+        return plan.flowsToRun.any { it.toFile().isWebFlow() } ||
                plan.sequence.flows.any { it.toFile().isWebFlow() }
     }
 
     private fun allFlowsAreWebFlow(plan: ExecutionPlan): Boolean {
-      return plan.flowsToRun.all { it.toFile().isWebFlow() }
+        if(plan.flowsToRun.isEmpty() && plan.sequence.flows.isEmpty()) return false
+        return (plan.flowsToRun.all { it.toFile().isWebFlow() } && plan.sequence.flows.all { it.toFile().isWebFlow() })
     }
```
Comment (amanjeetsingh150) [inline maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt:211]: Can we write a test for this function its too much logic and not tested. This might break again?

Comment (amanjeetsingh150) [reply maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt:211]: We should pull this logic behind a small abstraction so it’s testable. Then have minimal sample workspace we can run against that abstraction.

Comment (proksh) [reply maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt:211]: Added test for these.
