### PR TITLE
fix: text and id combined selector

### LINKED ISSUE #2533: [ios] using assertVisible with id and text doesn't work
### Is there an existing issue for this?

- [x] I have searched the existing issues and didn't find mine.

### Steps to reproduce

Create `Counter` component with

```
import React from 'react'
import { Text, View, TouchableOpacity, StyleSheet, useColorScheme } from 'react-native'
import { getFontStyles } from '@/constants/fontStyles'
import { ThemedText } from '@/components/ThemedText'
import { colors } from '@/constants/Colors'

const Counter = ({ 
  count, 
  onIncrease, 
  onDecrease, 
  containerStyle, 
  buttonStyle, 
  textStyle, 
  counterTextStyle,
  id
}) => {
  console.log(`${id}-count`)
    const colorScheme = useColorScheme()
    const fontStyles = getFontStyles(colorScheme)
    const styles = StyleSheet.create({
      container: {
        flexDirection: 'row',
      },
      button: {
        // backgroundColor: colors.mainBlue,
        width: 37,
        // borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
      },
      buttonText: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.appGreen,
      },
      counterText: {
        fontWeight: 'bold',
        margin: 5,
        textAlignVertical: 'center'
      },
      inactiveButton: {}
    });
  
    return (
        <View style={[styles.container, containerStyle]} accessible={true}>
          <TouchableOpacity 
            activeOpacity={0.8}
            disabled={count <= 1}
            onPress={onDecrease}
            style={[styles.button, count <= 1 && styles.inactiveButton, buttonStyle]}
            testID={`${id}-decrease`}
          >
              <Text style={[styles.buttonText, textStyle]}>-</Text>
          </TouchableOpacity>
          <Text 
            style={[fontStyles.smallText, counterTextStyle, styles.counterText, textStyle]}
            testID={`${id}-count`}
          >{count}</Text>
          <TouchableOpacity 
            activeOpacity={0.8} 
            onPress={onIncrease} 
            style={[styles.button, buttonStyle]}
            testID={`${id}-increase`}
          >
              <Text style={[styles.buttonText, textStyle]}>+</Text>
          </TouchableOpacity>
        </View>
    );
};

export default Counter;
```

Then use it like this:

```
<Counter
	id="contact-settings-counter"
	containerStyle={containerStyle}
	buttonStyle={buttonStyle}
	textStyle={textStyle}
	counterTextStyle={counterTextStyle}
	onIncrease={() => handleNumberOfMems(Number(countToNotify) + 1)}
	onDecrease={() => handleNumberOfMems(Number(countToNotify) - 1)}
	count={countToNotify}
/>
```

### Actual results

Image

### Expected results

I can target specific text inside of a specific id

### About app

Expo / React Native
Closed source

### About environment

Latest maestro
macOS
iOS 18.2

### Logs

_No response_

### Maestro version

1.40.3

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

### Anything else?

[hierarchy.log](https://github.com/user-attachments/files/20691921/hierarchy.log)

### PR DESCRIPTION
**Pull request by proksh**
PR Description: Fix deepestMatchingElement Filter Logic for Text and ID Selectors

## Summary
This PR fixes a issue with the deepestMatchingElement filter logic that was causing incorrect element selection when using `text` and `id` selectors. The fix ensures that the filter properly returns correct deepest matching elements in the UI hierarchy.

## Problem
The previous implementation of deepestMatchingElement had a flawed algorithm that would incorrectly select child elements even when matching selectors was pointing at parent. This caused issues with element selection, particularly when multiple nested elements matched any one selector from `text` or `id`.

## Changes Made

1. Improved Filter Composition Logic ([maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt](https://github.com/mobile-dev-inc/Maestro/pull/2711/files#diff-00989d49f0eaa1f9e614580322e3b2ec79d9915a804ffa004e2f53ba36215698))

Before: We were applying filters with `text` and only selecting deepestOne from there. Then again doing the same with `id`, which can give wrong result if `id` & `text` was some parent of first deepest selected node. ([Test 129](https://github.com/mobile-dev-inc/Maestro/pull/2711/files#diff-bb8086499ecc43e4b6eb8c6abca0d48b393ac903c3dd21461ae8686fa639e078))

- Separated filter types: Distinguished between "basic filters" (text, ID, size, traits, etc.) and "relative filters" (below, above, leftOf, rightOf, etc.)
- Applied `deepestMatchingElement` correctly: Now only applies to basic filters, not relative filters
- Better filter intersection: Properly combines basic and relative filters using intersection logic

2. Fixed `deepestMatchingElement` Algorithm ([maestro-client/src/main/java/maestro/Filters.kt](https://github.com/mobile-dev-inc/Maestro/pull/2711/files#diff-2dfb6ca77500e06b2fffc98666d632770fa0ccda87e1dacdc904b6ff8167e3b9))

Before: Used a flawed approach that would return parent elements even when children matched. It used to work because we were sending pre filtered nodes, but since we are not sending a combined basicFilter nodes, this would fail.

After: Implemented a proper recursive algorithm that:
- Recursively checks children first
- Returns children if they match the filter
- Only returns the parent if no children match
- Handles multiple root elements correctly
- Uses .distinct() to avoid duplicates

3. Added Tests for DeepestMatchingElementTest ([maestro-test/src/test/kotlin/maestro/test/DeepestMatchingElementTest.kt](https://github.com/mobile-dev-inc/Maestro/pull/2711/files#diff-76396e1c4f6bd44404de67c0b2f6cc222a53f2fe835ee7cadfa6b440ea5ee401))

4. Added tests for Integration Test for cases that were failing before ([maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt](https://github.com/mobile-dev-inc/Maestro/pull/2711/files#diff-5f00691128e9f122afec58e59902dd0e34941d9c943ee56859390061d0d08060))

Fixes #2533 and #2651

### CODE REVIEW

**Comment by Fishbowler** [comment]
Why wouldn't we take the first deepest matching element of all filters?

Isn't there a problem where we have:

```
tapOn:
  text: This One
  checked: true
```

But it doesn't match because deepestMatchingElement picks a different "This One"?

i.e. won't this problem apply to all "id + something" and "text + something" filters?

**Comment by proksh** [comment]
> Why wouldn't we take the first deepest matching element of all filters?
> 
> Isn't there a problem where we have:
> 
> ```
> tapOn:
>   text: This One
>   checked: true
> ```
> 
> But it doesn't match because deepestMatchingElement picks a different "This One"?
> 
> i.e. won't this problem apply to all "id + something" and "text + something" filters?

Ohh got it, but what about index? If I do:
```
tapOn:
  text: This One
  index: 2
```
Should it also count the nesting? Wont it lead to multiple count for that single element? Should this deepestMatchingElement be before index only?

**Comment by Fishbowler** [comment]
That makes sense.

The deepest matching element is to prevent getting a container rather than "the actual thing". And you can still end up with multiple matches, so indexes still make sense too.

**Comment by proksh** [comment]
> That makes sense.
> 
> The deepest matching element is to prevent getting a container rather than "the actual thing". And you can still end up with multiple matches, so indexes still make sense too.

Updated PR descriptions for the changes made.

**Comment by proksh** [comment]
I have tested this on some workspace

@Fishbowler It would be great if you can test in some workspace that you know use alot of combined selector to be sure this is not breaking anything.

File: maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt [hunk 1]
```diff
@@ -3912,6 +3912,78 @@ class IntegrationTest {
             }
         }
     }
+
+    @Test
+    fun `Case 129 - Text and ID with child elements`() {
```
Comment (amanjeetsingh150) [inline maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt:3917]: Nice!
